### ISSUE TITLE
Child Filter Box Remains 

### ISSUE THREAD

**Issue by JRycr** [SocialFinanceDigitalLabs/quality-lac-data-beta#46]
Once the validation has run the list of child id's on left hand side has the "child filter" next to it. When I click on this a dialogue box pops up but can't cancel out of it.

<img width="490" alt="Capture" src="https://user-images.githubusercontent.com/88544325/130435867-5d1a73b1-d78f-4ae3-a0a1-3478ce53a1b1.PNG">

Could there be a cancel button?

**Comment by mwaddoups** [comment]
Good one - if you click Filter again it should close, but I agree it's not very intuitive - I'll add an x button.

**Comment by mwaddoups** [comment]
I have now added an x button and click-outside to close (in #48) - so we can close this one I think.
