### ISSUE TITLE
Filter box overflowing

### ISSUE THREAD

**Issue by mwaddoups** [SocialFinanceDigitalLabs/quality-lac-data-beta#51]
Our filter box doesn't currently add a scrollbar when the number of errors overflow - we need to add this.

**Comment by mikejarmstrong** [comment]
Is this the issue illustrated in the attached image? If so then I agree!
Also, can these errors be sorted (probably by number) in this list to make them easier to find?
<img width="800" alt="Filter list" src="https://user-images.githubusercontent.com/90046836/132010914-8ac1e7b3-fe92-488d-8675-4532642601b7.png">

**Comment by mwaddoups** [comment]
Really helpful - yes we will do both of those things

**Comment by mwaddoups** [comment]
On the sorting - currently they are sorted by the error with the highest number of occurences - not sure if sorting by number is better?

**Comment by mikejarmstrong** [comment]
I don't know how everyone else works - but when I'm addressing errors in my 903 data I try to deal with all of the similar errors at the same time - so if I've summoned up the courage to tidy up all of the postcode problems then I want to identify them - and to do that I'd currently have to find out how many of them there are and then scroll down to find them. I already know the error IDs, so if they were sorted in that order I could scroll straight to them. Also, if I fix half of them and then re-filter I have to go and look up how many there are now before I can find them again.
Obviously others may work differently though...

**Comment by mwaddoups** [comment]
That makes a lot of sense - I think there are a few cases like this where we might want to allow for different sorting. I'll have a think about how we can implement it.

**Comment by SLornieCYC** [comment]
Yeah, I think this is something that has multiple use-cases: 

1) load data and get a quick sense of where the errors are (sorted by number of errors)
2) load data and review/work on a specific error (sorted by error code for ease of finding)

To be honest though *any* form of sorting would be an improvement over the reporting DFE provide in the submission portal!

Stretch goal: I'm not sure whether DFEs concept of Stage 1 and Stage 2 errors has come up in this project yet but being able to sort based on that might be something worth considering too, or even just a way to flag that an error is Stage 1.  Less directly important if this tool doesn't suppress S2 errors where S1 errors also exist but helpful for context and in comparison with what we'll be seeing at year-end.

**Comment by dezog** [comment]
closed by https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta/commit/0e62996b2a3d99c3c1b384bcec0cb8c1601bac69
