### ISSUE TITLE
LA list

### ISSUE THREAD

**Issue by mikejarmstrong** [SocialFinanceDigitalLabs/quality-lac-data-beta#54]
When uploading the dummy data there's a list of LAs to choose from. I left it on the default of Aberdeen City - but that doesn't seem to make any difference later on - what's it for?
If it useful then can you remove the Scottish LAs from the list? They don't submit 903 data (do the Welsh ones??) so they're just taking up scrolling space

**Comment by mikejarmstrong** [comment]
..same applies to Northern Irish LAs

**Comment by mwaddoups** [comment]
Thanks - this is helpful.

The LA data is used in some of the validation rules - e.g. if I recall correctly, a rule checks that placement postcodes are in the local authority of the filer.

In theory, if you set it once (to your LA) the browser should remember your choice for next time.

Agree that we can remove the Scottish and Welsh LAs though - I will have a look at that

**Comment by mikejarmstrong** [comment]
Thanks for removing the extras.
Presumably the browser remembers your LA via a cookie? If so I have mine set to clear every time my browser closes...but that's my problem not yours!

**Comment by mwaddoups** [comment]
It's stored in local storage rather than a cookie - but if you have your browser set up to clear local data I imagine that might get purged too!

I've updated the LA list and changes should be live shortly.
