### ISSUE TITLE
Null/blank data should not be replaced with N/A on the front-end

### ISSUE THREAD

**Issue by SLornieCYC** [SocialFinanceDigitalLabs/quality-lac-data-beta#55]
At the moment null (missing/blank) data items are shown as "N/A" in the front-end.  For example where UPN hasn't been provided, or the fields DEC and REC on an open episode.  

This is misleading because:

1) it does not correctly reflect the underlying data 
2) it is unclear whether N/A means "Not Available" or "Not Applicable" (e.g. MOTHER and MC_DOB fields on a male child record).

**Comment by dezog** [comment]
This is a good point - "N/A" does seem to imply the missing value _ought_ to be missing, as in your (2). 

This should be changed to say something like **NULL**, or **MISSING** - any thoughts on what would feel most natural here?

I'll have to have a look into how this part of the frontend code works (bear with me, I'm by no means a javascript person), or get @kws on the case, but it feels like this should be an easy fix that we can take care of within the next week.

**Comment by SLornieCYC** [comment]
For me **NULL** seems more appropriate.  That describes the absence of data without making any "judgement" about it (for want of a better word!) - to me MISSING implies that there should be a value present (which we know is not always the case).

**Comment by dezog** [comment]
(Closed this and opened #59 to address adding a different style to blank cells)
